version: '3.8'

services:
  hotel-mysql:
    image: mysql:8.0
    container_name: hotel-mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=hotel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user